{
 "title": "AlertManager",
 "description": "AlertManager handles alerts from Prometheus",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(alertmanager_build_info, instance)"
   },
   {
    "name": "receiver",
    "query": "label_values(alertmanager_notifications_total, integration)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Profile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"\"}[5m])",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=\"\"})",
     "legendFormat": "process resident memory"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"\"}",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "Memory allocation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(go_memstats_mallocs_total{instance=~\"\"}[5m])",
     "legendFormat": "malloc"
    },
    {
     "expr": "irate(go_memstats_frees_total{instance=~\"\"}[5m])",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertmanager_cluster_members{instance=~\"\"}"
    }
   ]
  },
  {
   "title": "Reload status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alertmanager_alerts{instance=~\"\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Alert ingestion rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(alertmanager_alerts_received_total{instance=~\"\"}[5m])",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "irate(alertmanager_alerts_invalid_total{instance=~\"\"}[5m])",
     "legendFormat": "invalid"
    }
   ]
  },
  {
   "title": "Silences",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alertmanager_silences{instance=~\"\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Silence QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(alertmanager_silences_query_duration_seconds_count{instance=~\"\"}[5m])",
     "legendFormat": "total"
    },
    {
     "expr": "irate(alertmanager_silences_query_errors_total{instance=~\"\"}[5m])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Silence query latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(alertmanager_silences_query_duration_seconds_bucket{instance=~\"\"}[5m]))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, rate(alertmanager_silences_query_duration_seconds_bucket{instance=~\"\"}[5m]))",
     "legendFormat": "median"
    },
    {
     "expr": "rate(alertmanager_silences_query_duration_seconds_sum{instance=~\"\"}[5m]) / rate(alertmanager_silences_query_duration_seconds_count{instance=~\"\"}[5m])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Notification logs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(alertmanager_notifications_total{instance=~\"\",integration=~\"\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(irate(alertmanager_notifications_failed_total{instance=~\"\",integration=~\"\"}[5m]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Notification log  QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(alertmanager_nflog_query_duration_seconds_count{instance=~\"\"}[5m])",
     "legendFormat": "queries"
    },
    {
     "expr": "irate(alertmanager_nflog_query_errors_total{instance=~\"\"}[5m])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Notification log query latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"\"}[5m]))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, rate(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"\"}[5m]))",
     "legendFormat": "median"
    },
    {
     "expr": "rate(alertmanager_nflog_query_duration_seconds_sum{instance=~\"\"}[5m]) / rate(alertmanager_nflog_query_duration_seconds_count{instance=~\"\"}[5m])",
     "legendFormat": "average"
    }
   ]
  }
 ]
}